#!/bin/bash

# Check if the script is run as root
if [ "$(id -u)" != "0" ]; then
    echo "Error: Skrip ini harus dijalankan sebagai root."
    exit 1
fi
clear
# Mengambil nilai domain, port dan token dari file
domain=$(cat /etc/data/domain)
token=$(cat /etc/data/token.json | jq -r .access_token)
port=$(netstat -tunlp | grep 'python' | awk '{split($4, a, ":"); print a[2]}')

# Meminta input pengguna
while true; do
    read -rp "Username: " -e user

    # Validasi panjang karakter
    if [[ ${#user} -lt 4 || ${#user} -gt 32 ]]; then
        echo "Username harus memiliki panjang minimal 4 karakter dan maksimal 32 karakter."
        continue
    fi

    # Validasi karakter tanpa spesial karakter
    if [[ ! "$user" =~ ^[a-zA-Z0-9_]+$ ]]; then
        echo "Username hanya dapat mengandung huruf, angka, dan underscore (_) tanpa karakter spesial."
        continue
    fi

    TOTAL_USERS=$(curl -s -X 'GET' \
        "https://${domain}:${port}/api/users?username=${user}" \
        -H 'accept: application/json' \
        -H "Authorization: Bearer ${token}" \
        | jq -r '.total')

    if [[ ${TOTAL_USERS} == '1' ]]; then
        echo ""
        echo "Klien dengan username ${user} sudah terdaftar pada database, mohon gunakan username lain."
        exit 1
    fi

    # Jika semua validasi terpenuhi, keluar dari loop
    break
done

read -rp "Catatan user: " -e catatan
echo "Masa aktif"
echo "[biarkan kosong atau tekan saja enter jika tidak butuh masa aktif / AlwaysON]"
read -p "Expired (Hari): " masaaktif
echo "[biarkan kosong atau tekan saja enter jika ingin sett Unlimited Quota]"
read -rp "Quota (GB): " -e gb

if [ -n "$gb" ]; then
    limitq=$((gb * 1024**3))
    quota_text="${gb} GB"

# Menampilkan opsi reset data
echo "Pilih jenis siklus reset data:"
echo "1. Tanpa ada reset"
echo "2. Harian"
echo "3. Mingguan"
echo "4. Bulanan"
echo "5. Tahunan"

# Menerima input pilihan pengguna
read -p "Masukkan nomor pilihan Anda: " choice

# Memilih strategi reset berdasarkan pilihan pengguna
case $choice in
    1)
        reset_strategy="no_reset"
        ;;
    2)
        reset_strategy="day"
        ;;
    3)
        reset_strategy="week"
        ;;
    4)
        reset_strategy="month"
        ;;
    5)
        reset_strategy="year"
        ;;
    *)
        echo "Pilihan tidak valid."
        exit 1
        ;;
esac
    
else
    limitq=0
    quota_text="Unlimited"
    reset_strategy="no_reset"
fi

# Menggunakan variable uuid untuk generate password
uuid=$(cat /proc/sys/kernel/random/uuid)

if [ -n "$masaaktif" ]; then
    exp="$(date -d "${masaaktif} days" +"%s")"
    exp2=$(date -d "${masaaktif} days" +"%Y-%m-%d")
else
    exp=0
    exp2=AlwaysON
fi

# Mengirimkan permintaan ke API
curl -X 'POST' \
  "https://${domain}:${port}/api/user" \
  -H 'accept: application/json' \
  -H "Authorization: Bearer ${token}" \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "'"${user}"'",
  "proxies": {
    "vless": {
      "id": "'"${uuid}"'",
      "flow": ""
    }
  },
  "inbounds": {
    "vless": [
      "VLESS_WS",
      "VLESS_HU",
      "VLESS_GRPC"
    ]
  },
  "expire": '"${exp}"',
  "data_limit": '"${limitq}"',
  "data_limit_reset_strategy": "'"${reset_strategy}"'",
  "status": "active",
  "note": "'"${catatan}"'"
}' > /tmp/${user}_vless.json
subs=$(cat /tmp/${user}_vless.json | jq -r .subscription_url)

# Link VLess
vlesslink1="vless://${uuid}@${domain}:443?security=tls&type=ws&host=${domain}&headerType=&path=%2Fvless&sni=&fp=&alpn=http%2F1.1#%28${user}%29%20%5BVLESS%20-%20WS%5D%20TLS"
vlesslink2="vless://${uuid}@${domain}:80?security=none&type=ws&host=${domain}&headerType=&path=%2Fvless#%28${user}%29%20%5BVLESS%20-%20WS%5D%20nonTLS"
vlesslink3="vless://${uuid}@${domain}:443?security=tls&type=grpc&host=${domain}&headerType=&serviceName=vless-service&sni=${domain}&fp=&alpn=h2#%28${user}%29%20%5BVLESS%20-%20GRPC%5D%20TLS"
vlesslink4="vless://${uuid}@${domain}:443?security=tls&type=httpupgrade&host=${domain}&headerType=&path=%2Fvlessupgrade&sni=&fp=&alpn=http%2F1.1#%28${user}%29%20%5BVLESS%20-%20HTTPUpgrade%5D%20TLS"
vlesslink5="vless://${uuid}@${domain}:80?security=none&type=httpupgrade&host=${domain}&headerType=&path=%2Fvlessupgrade#%28${user}%29%20%5BVLESS%20-%20HTTPUpgrade%5D%20nonTLS"
clear
echo -e ""
echo -e "=======-XRAY/VLESS======="
echo -e ""
echo -e "Remarks: ${user}"
echo -e "Domain: ${domain}"
echo -e "Quota: ${quota_text}"
# Replace values and specific reset strategies
  case "${reset_strategy}" in
    "no_reset") reset_strategy="Loss_doll";;
    "day") reset_strategy="Harian";;
    "week") reset_strategy="Mingguan";;
    "month") reset_strategy="Bulanan";;
    "year") reset_strategy="Tahunan";;
esac
echo -e "Reset Quota Strategy: ${reset_strategy}"
echo -e "================================="
echo -e "🔑 Port TLS: 443, 8443, 8880"
echo -e "🔑 Port nonTLS: 80, 2082, 2083, 3128, 8080"
echo -e "================================="
echo -e "id: ${uuid}"
echo -e "decryption: none"
echo -e "================================="
echo -e "network: ws/httpupgrade/grpc"
echo -e "================================="
echo -e "path Websocket, HTTPUpgrade & gRPC serviceName: "
echo -e "a.) WS: /vless atau /enter-your-custom-path/vless"
echo -e "b.) GRPC: vless-service"
echo -e "c.) HU: /vlessupgrade"
echo -e "================================="
echo -e "alpn: "
echo -e "a.) WS/HU: http/1.1"
echo -e "b.) GRPC: h2"
echo -e "================================="
echo -e "tls:"
echo -e "a.) WS/HU: true (tls), false (nontls)"
echo -e "b.) GRPC: true"
echo -e "================================="
echo -e "allowInsecure: true"
echo -e "================================="
echo -e "VLess-WS TLS: ${vlesslink1}"
echo -e "================================="
echo -e "VLess-WS nTLS: ${vlesslink2}"
echo -e "================================="
echo -e "VLess-HU TLS: ${vlesslink4}"
echo -e "================================="
echo -e "VLess-HU nTLS: ${vlesslink5}"
echo -e "================================="
echo -e "VLess-gRPC TLS: ${vlesslink3}"
echo -e "================================="
echo -e "Link Subscription : https://${domain}:${port}${subs}"
echo -e "================================="
echo -e "Masa Aktif: ${exp2}"
rm -r /tmp/${user}_vless.json
